
version: '3'
services:
  mongodb:
    build: mongodb/
    image: hermesdemo/mongo
    restart: always
    container_name: wave-demo_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "37017:27017"
    volumes:
       - $HOME/data:/data/db
    networks:
      - wave-demo

  mongo-express:
    image: mongo-express
    container_name: wave-demo_mongoexpress
    restart: always
    ports:
      - "9081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_SERVER: wave-demo_mongodb
    networks:
      - wave-demo

  users-service:
    image: waveim/demo-users-service:latest
    container_name: wave-demo-users-service
    restart: always
    ports:
      - "8086:8086"
    networks:
      - wave-demo


networks:
  wave-demo:
    driver: "bridge"
