
version: '3'
services:
  mongodb:
    build: mongodb/
    image: hermesdemo/mongo
    restart: always
    container_name: hermes-demo_mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "37017:27017"
    volumes:
       - $HOME/data:/data/db
    networks:
      - hermes-demo

  mongo-express:
    image: mongo-express
    container_name: hermes-demo_mongoexpress
    restart: always
    ports:
      - "9081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_SERVER: hermes-demo_mongodb
    networks:
      - hermes-demo


networks:
  hermes-demo:
    driver: "bridge"
